services:
  front-end:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: frontend.dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./front-end/.env:/app/.env
  broker:
    container_name: broker
    build:
      context: ./broker
      dockerfile: broker.dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./broker/.env:/app/.env
  member-service:
    container_name: member-service
    build:
      context: ./member-service
      dockerfile: member-service.dockerfile
    ports:
      - "8083:80"
      - "8084:81"
    volumes:
      - ./member-service/.env:/app/.env
  postgres17:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54317:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres17_data:
